<?php require_once("legvel.php"); 
include 'menu.php'; ?>
<html>
<head>

</head>
<body>

<style type="text/css">
<!--
a.type1 { color: red; }
a.type1:link,hover { 
text-decoration:none;
color: yellow;}

a.type2 { color: blue;
text-decoration:none; }
a.type2:link,hover { color: green; }
-->
</style>

<style type="text/css">
 <!-- 
.Style1 {
	color:#008080;
	font-weight: bold;
}
.Style2 {color: #000080}
-->

<!-- 
.style44{
	font-family:"Segeo UI",Calibri;
}
-->

</style>

<body background="images/s.png"><font face="calibri" >
 



<table align="center" border="0" cellpadding="0"><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<tr>
	<td><BIG><BIG><BIG><a href="listpass.php" class="type2" ><img src='images/pe.png'></a></BIG></BIG></BIG></td>
	<td><BIG><BIG><BIG><a href="listbagage.php" class="type2" ><img src='images/ba.png'></a></BIG></BIG></BIG></td>
	<td><BIG><BIG><BIG><a href="listargent.php" class="type2" ><img src='images/ar.png'></a></BIG></BIG></BIG></td>
	</tr>

</table>
<br><br><br><br><br><br><br><br><br><br><br>



</body>
</html>